export const IS_VISIBLE_CATEGORY_FORM = "is_visible_category_form";
export const IS_VISIBLE_ORDER_FORM = "is_visible_order_form";
export const IS_VISIBLE_PRODUCT_FORM = "is_visible_product_form";
export const IS_VISIBLE_CUSTOMER_FORM = "is_visible_customer_form";
export const IS_VISIBLE_ACCOUNT_FORM = "is_visible_account_form";
export const IS_VISIBLE_PROMOTION_FORM = "is_visible_promotion_form";
export const IS_VISIBLE_STORE_FORM = "is_visible_store_form";
export const IS_EDIT_CATEGORY_FORM = "is_edit_category_form";
export const IS_EDIT_PRODDUCT_FORM = "is_edit_product_form";
export const IS_EDIT_ACCOUNT_FORM = "is_edit_account_form";
export const IS_EDIT_CUSTOMER_FORM = "is_edit_customer_form";
export const IS_EDIT_PROMOTION_FORM = "is_edit_promotion_form";
export const IS_EDIT_STORE_FORM = "is_edit_store_form";
export const SET_ID_CATEGORY = "set_id_category_form";
export const SET_ID_GROUP_PERMISSION = "set_id_group_permission_form";
export const SET_ID_PRODUCT = "set_id_product_form";
export const SET_ID_ORDER = "set_id_order";
export const SET_ID_CUSTOMER = "set_id_customer";
export const SET_ID_ACCOUNT = "set_id_account";
export const SET_ID_PROMOTION = "set_id_promotion";
export const SET_ID_STORE = "set_id_store";
export const SET_VARIANT = "set_variant";

export enum ActionType {
  IS_VISIBLE_CATEGORY_FORM = "is_visible_category_form",
  IS_VISIBLE_ORDER_FORM = "is_visible_order_form",
  IS_VISIBLE_PRODUCT_FORM = "is_visible_product_form",
  IS_VISIBLE_CUSTOMER_FORM = "is_visible_customer_form",
  IS_VISIBLE_ACCOUNT_FORM = "is_visible_account_form",
  IS_VISIBLE_PROMOTION_FORM = "is_visible_promotion_form",
  IS_VISIBLE_STORE_FORM = "is_visible_store_form",
  IS_EDIT_CATEGORY_FORM = "is_edit_category_form",
  IS_EDIT_PRODDUCT_FORM = "is_edit_product_form",
  IS_EDIT_ACCOUNT_FORM = "is_edit_account_form",
  IS_EDIT_CUSTOMER_FORM = "is_edit_customer_form",
  IS_EDIT_PROMOTION_FORM = "is_edit_promotion_form",
  IS_EDIT_STORE_FORM = "is_edit_store_form",
  SET_ID_CATEGORY = "set_id_category_form",
  SET_ID_GROUP_PERMISSION = "set_id_group_permission_form",
  SET_ID_PRODUCT = "set_id_product_form",
  SET_ID_ORDER = "set_id_order",
  SET_ID_CUSTOMER = "set_id_customer",
  SET_ID_ACCOUNT = "set_id_account",
  SET_ID_PROMOTION = "set_id_promotion",
  SET_ID_STORE = "set_id_store",
  SET_VARIANT = "set_variant",
}
